/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author GGG
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        box1 = new javax.swing.JButton();
        box2 = new javax.swing.JButton();
        box3 = new javax.swing.JButton();
        box4 = new javax.swing.JButton();
        box5 = new javax.swing.JButton();
        box6 = new javax.swing.JButton();
        box7 = new javax.swing.JButton();
        box8 = new javax.swing.JButton();
        box9 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(255, 204, 204));
        getContentPane().setLayout(null);

        box1.setText("1");
        box1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box1ActionPerformed(evt);
            }
        });
        getContentPane().add(box1);
        box1.setBounds(0, 0, 96, 75);

        box2.setText("2");
        box2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box2ActionPerformed(evt);
            }
        });
        getContentPane().add(box2);
        box2.setBounds(102, 0, 95, 75);

        box3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box3ActionPerformed(evt);
            }
        });
        getContentPane().add(box3);
        box3.setBounds(203, 0, 94, 75);

        box4.setText("4");
        box4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box4ActionPerformed(evt);
            }
        });
        getContentPane().add(box4);
        box4.setBounds(1, 81, 95, 74);

        box5.setText("5");
        box5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box5ActionPerformed(evt);
            }
        });
        getContentPane().add(box5);
        box5.setBounds(102, 81, 95, 74);

        box6.setText("6");
        box6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box6ActionPerformed(evt);
            }
        });
        getContentPane().add(box6);
        box6.setBounds(203, 81, 94, 74);

        box7.setText("7");
        box7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box7ActionPerformed(evt);
            }
        });
        getContentPane().add(box7);
        box7.setBounds(0, 161, 95, 75);

        box8.setText("8");
        box8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box8ActionPerformed(evt);
            }
        });
        getContentPane().add(box8);
        box8.setBounds(102, 161, 95, 75);

        box9.setText("3");
        box9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box9ActionPerformed(evt);
            }
        });
        getContentPane().add(box9);
        box9.setBounds(203, 161, 94, 75);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void box1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box1ActionPerformed
        if(box2.isVisible()==false){        // TODO add your handling code here:
        box2.setText(box1.getText());
        box1.setVisible(false);
        box2.setVisible(true);
    }//GEN-LAST:event_box1ActionPerformed

        if(box4.isVisible()==false){
        box4.setText(box1.getText());
        box1.setVisible(false);
        box4.setVisible(true);
    }
        if(box1.getText()=="1"&&box2.getText()=="2"&&box3.getText()=="3"&&box4.getText()=="4"&&box5.getText()=="5"&&box6.getText()=="6"&&box7.getText()=="7"&&box8.getText()=="8") {
            winner();
        }
    }
    private void box2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box2ActionPerformed
        if(false==box1.isVisible()){// TODO add your handling code here:
        box1.setText(box2.getText());
        box2.setVisible(false);
        box1.setVisible(true);    
        }
        
        if(box3.isVisible()==false){
        box3.setText(box2.getText());
        box2.setVisible(false);
        box3.setVisible(true);
        }
        
        if(box5.isVisible()==false){
        box5.setText(box2.getText());
        box2.setVisible(false);
        box5.setVisible(true);
        }
        if(box1.getText()=="1"&&box2.getText()=="2"&&box3.getText()=="3"&&box4.getText()=="4"&&box5.getText()=="5"&&box6.getText()=="6"&&box7.getText()=="7"&&box8.getText()=="8") {
            winner();
    }//GEN-LAST:event_box2ActionPerformed
    }
    private void box3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box3ActionPerformed
        if(box2.isVisible()==false){ // TODO add your handling code here:
        box2.setText(box3.getText());
        box3.setVisible(false);
        box2.setVisible(true);
        }
        if(box6.isVisible()!=false){
        box6.setText(box3.getText());
        box3.setVisible(false);
        box6.setVisible(true);
        }
        if(box1.getText()=="1"&&box2.getText()=="2"&&box3.getText()=="3"&&box4.getText()=="4"&&box5.getText()=="5"&&box6.getText()=="6"&&box7.getText()=="7"&&box8.getText()=="8") {
            winner();
    }                     
    }//GEN-LAST:event_box3ActionPerformed

    private void box5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box5ActionPerformed
        if(box4.isVisible()==false){ // TODO add your handling code here:
        box4.setText(box5.getText());
        box5.setVisible(false);
        box4.setVisible(true);
        }
        if(box6.isVisible()==false){
        box6.setText(box5.getText());
        box5.setVisible(false);
        box6.setVisible(true);
        }
        if(box2.isVisible()==false){
        box2.setText(box5.getText());
        box5.setVisible(false);
        box2.setVisible(true);
        }
        if(box8.isVisible()==false){
        box8.setText(box5.getText());
        box5.setVisible(false);
        box8.setVisible(true);
        }
        if(box1.getText()=="1"&&box2.getText()=="2"&&box3.getText()=="3"&&box4.getText()=="4"&&box5.getText()=="5"&&box6.getText()=="6"&&box7.getText()=="7"&&box8.getText()=="8") {
            winner();
    }                     
    }//GEN-LAST:event_box5ActionPerformed

    private void box4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box4ActionPerformed
        if(box1.isVisible()==false){ // TODO add your handling code here:
        box1.setText(box4.getText());
        box4.setVisible(false);
        box1.setVisible(true);
        }
        if(box5.isVisible()==false){
        box5.setText(box4.getText());
        box4.setVisible(false);
        box5.setVisible(true);
        }
        if(box7.isVisible()==false){
        box7.setText(box4.getText());
        box4.setVisible(false);
        box7.setVisible(true);
        }
        if(box1.getText()=="1"&&box2.getText()=="2"&&box3.getText()=="3"&&box4.getText()=="4"&&box5.getText()=="5"&&box6.getText()=="6"&&box7.getText()=="7"&&box8.getText()=="8") {
            winner();
    }//GEN-LAST:event_box4ActionPerformed
    }
    private void box6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box6ActionPerformed
        if(box3.isVisible()==false){ // TODO add your handling code here:
        box3.setText(box6.getText());
        box6.setVisible(false);
        box3.setVisible(true);
        }
        if(box5.isVisible()==false){
        box5.setText(box6.getText());
        box6.setVisible(false);
        box5.setVisible(true);
        }
        if(box9.isVisible()==false){
        box9.setText(box6.getText());
        box6.setVisible(false);
        box9.setVisible(true);
        }
        if(box1.getText()=="1"&&box2.getText()=="2"&&box3.getText()=="3"&&box4.getText()=="4"&&box5.getText()=="5"&&box6.getText()=="6"&&box7.getText()=="7"&&box8.getText()=="8") {
            winner();
    }              
    }//GEN-LAST:event_box6ActionPerformed

    private void box7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box7ActionPerformed
        if(box4.isVisible()==false){ // TODO add your handling code here:
        box4.setText(box7.getText());
        box7.setVisible(false);
        box4.setVisible(true);
        }
        if(box8.isVisible()==false){
        box8.setText(box7.getText());
        box7.setVisible(false);
        box8.setVisible(true);
        }
        if(box1.getText()=="1"&&box2.getText()=="2"&&box3.getText()=="3"&&box4.getText()=="4"&&box5.getText()=="5"&&box6.getText()=="6"&&box7.getText()=="7"&&box8.getText()=="8") {
            winner();
    }              
    }//GEN-LAST:event_box7ActionPerformed

    private void box8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box8ActionPerformed
        if(box5.isVisible()==false){ // TODO add your handling code here:
        box5.setText(box8.getText());
        box8.setVisible(false);
        box5.setVisible(true);
        }
        if(box7.isVisible()==false){
        box7.setText(box8.getText());
        box8.setVisible(false);
        box7.setVisible(true);
        }
        if(box9.isVisible()==false){
        box9.setText(box8.getText());
        box8.setVisible(false);
        box9.setVisible(true);
        }
        if(box1.getText()=="1"&&box2.getText()=="2"&&box3.getText()=="3"&&box4.getText()=="4"&&box5.getText()=="5"&&box6.getText()=="6"&&box7.getText()=="7"&&box8.getText()=="8") {
            winner();
    }              
    }//GEN-LAST:event_box8ActionPerformed

    private void box9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box9ActionPerformed
        if(box9 == null){  // TODO add your handling code here:
        }
    }//GEN-LAST:event_box9ActionPerformed
       
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton box1;
    private javax.swing.JButton box2;
    private javax.swing.JButton box3;
    private javax.swing.JButton box4;
    private javax.swing.JButton box5;
    private javax.swing.JButton box6;
    private javax.swing.JButton box7;
    private javax.swing.JButton box8;
    private javax.swing.JButton box9;
    // End of variables declaration//GEN-END:variables
private void winner() {
        System.out.println("You win2");
//throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
}

